---
baseURL: "/resumecards/" # The subpath of your site. Use "" if you're hosting a blog at the root level.
title: "ResumeCards, a Markdown based resume generator."

ignoreFiles:
  - "README.md"
  - "CHANGELOG.md"
  - "CNAME"